# Introduction à l'apprentissage profond
# Tutoriel PyTorch

**Objectifs pédagogiques :**
- Comprendre ce qu'est PyTorch et pourquoi il est utilisé en apprentissage profond
- Maîtriser les opérations et manipulations de tenseurs
- Découvrir la différentiation automatique (autograd)
- Construire et entraîner un réseau de neurones simple

---


## Qu'est-ce que PyTorch ?

> PyTorch est une plateforme open source d'apprentissage profond qui offre un passage fluide du prototypage de recherche au déploiement en production.
>
> **Fonctionnalités clés :**
> - **Graphes de calcul dynamiques** : construction de graphes à la volée, pour plus de flexibilité
> - **Conception centrée sur Python** : intégration étroite avec l'écosystème Python
> - **Accélération GPU performante** : prise en charge fluide de CUDA
> - **Écosystème riche** : outils de vision par ordinateur, de NLP et plus encore
>
> — *[PyTorch.org](https://pytorch.org/)*

### Pourquoi PyTorch ?

PyTorch est devenu l'un des frameworks d'apprentissage profond les plus populaires grâce à :
1. **API intuitive** : facile à apprendre et à utiliser, particulièrement pour les développeurs Python
2. **Débogage** : les outils de débogage Python standard fonctionnent de manière fluide
3. **Adapté à la recherche** : apprécié des chercheurs pour sa flexibilité
4. **Prêt pour la production** : utilisé en production par des entreprises comme Meta, Tesla et bien d'autres

**Ressources :**
- [Documentation officielle](https://pytorch.org/docs/stable/index.html)
- [Tutoriels PyTorch](https://pytorch.org/tutorials/)
- [Guide PyTorch de Nvidia](https://www.nvidia.com/en-us/glossary/data-science/pytorch/)

---


## 1. Installer PyTorch

Dans Google Colab, PyTorch est généralement préinstallé. Sinon, installez-le avec :

```bash
pip install torch torchvision
```

Pour des instructions d'installation spécifiques (CPU/GPU, différentes versions de CUDA), consultez : https://pytorch.org/get-started/locally/


In [ ]:
# Vérifier si PyTorch est installé
#!pip install torch torchvision --quiet

## 2. Importer les bibliothèques

Importons les bibliothèques nécessaires :


In [2]:
import torch
import numpy as np

# Vérifier la version de PyTorch
print(f"Version de PyTorch : {torch.__version__}")
print(f"CUDA disponible : {torch.cuda.is_available()}")
print(f"mps disponible : {torch.backends.mps.is_built()}")

Version de PyTorch : 2.8.0
CUDA disponible : False
mps disponible : True


## 3. Les tenseurs : les briques de base

**Qu'est-ce qu'un tenseur ?**

Un tenseur est un tableau multidimensionnel, similaire aux tableaux NumPy mais doté de capacités supplémentaires :
- Peut s'exécuter sur des GPU pour des calculs plus rapides
- Prend en charge la différentiation automatique (essentielle pour entraîner des réseaux de neurones)

**Dimensions des tenseurs :**
- Tenseur 0D (scalaire) : `5`
- Tenseur 1D (vecteur) : `[1, 2, 3]`
- Tenseur 2D (matrice) : `[[1, 2], [3, 4]]`
- Tenseur 3D+ : tableaux de dimension supérieure (p. ex. images, vidéos)

### 3.1 Créer des tenseurs à partir de listes Python


In [4]:
# Créer un tenseur 2D à partir d’une liste
x_list = [[1, 3, 5],
          [2, 4, 6]]

x_tensor = torch.tensor(x_list, dtype=torch.float64)  # Spécifier le type de données
print("Tenseur :")
print(x_tensor)
print(f"\nForme : {x_tensor.shape}")        # Dimensions du tenseur
print(f"Dimension : {x_tensor.ndim}")      # Nombre de dimensions
print(f"Type de données : {x_tensor.dtype}")     # Type de données des éléments
print(f"Taille : {x_tensor.size()}")         # Autre façon d’obtenir la forme

Tenseur :
tensor([[1., 3., 5.],
        [2., 4., 6.]], dtype=torch.float64)

Forme : torch.Size([2, 3])
Dimension : 2
Type de données : torch.float64
Taille : torch.Size([2, 3])


### 3.2 Conversion entre PyTorch et NumPy

Les tenseurs PyTorch et les tableaux NumPy se convertissent facilement l'un dans l'autre. Ils partagent souvent la même mémoire ; les modifications de l'un affectent donc l'autre !


In [5]:
x_tensor 

tensor([[1., 3., 5.],
        [2., 4., 6.]], dtype=torch.float64)

In [6]:
# Tenseur vers NumPy
x_np = x_tensor.numpy()


In [7]:
print("Tableau NumPy :")
print(x_np)
print(f"Type : {type(x_np)}")

Tableau NumPy :
[[1. 3. 5.]
 [2. 4. 6.]]
Type : <class 'numpy.ndarray'>


In [8]:
# NumPy vers tenseur
x_tensor_back = torch.from_numpy(x_np)


In [9]:
print("Retour au tenseur :")
print(x_tensor_back)
print(f"Type : {type(x_tensor_back)}")

Retour au tenseur :
tensor([[1., 3., 5.],
        [2., 4., 6.]], dtype=torch.float64)
Type : <class 'torch.Tensor'>


## 4. Créer des tenseurs

PyTorch fournit de nombreuses fonctions pratiques pour créer des tenseurs avec des valeurs ou des motifs spécifiques.

### 4.1 Zéros et uns


In [12]:
# Tenseur rempli de zéros
zero_tensor = torch.zeros(2, 3)  # 2 lignes, 3 colonnes
print("Zéros :")
print(zero_tensor)

Zéros :
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
# Tenseur rempli de uns
ones_tensor = torch.ones(3, 3)
print("Uns :")
print(ones_tensor)

Uns :
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


### 4.2 Remplis avec des valeurs spécifiques


In [18]:
# Tenseur rempli d’une valeur spécifique
full_tensor = torch.full(
                        (4, 3), 
                        fill_value=6.5)


In [19]:
print("Rempli avec 6.5 :")
print(full_tensor)

Rempli avec 6.5 :
tensor([[6.5000, 6.5000, 6.5000],
        [6.5000, 6.5000, 6.5000],
        [6.5000, 6.5000, 6.5000],
        [6.5000, 6.5000, 6.5000]])


### 4.3 Tenseurs aléatoires

Les tenseurs aléatoires sont couramment utilisés pour :
- Initialiser les poids des réseaux de neurones
- Créer des données de test
- Augmenter les données


In [20]:
# Tenseur aléatoire de distribution normale standard (moyenne=0, écart-type=1)
random_tensor = torch.randn(2, 3)
print("Tenseur aléatoire (distribution normale) :")
print(random_tensor)



Tenseur aléatoire (distribution normale) :
tensor([[-0.5091, -0.2424, -0.8167],
        [ 0.7084, -0.5303,  1.8917]])


In [21]:
# Tenseur aléatoire de distribution uniforme [0, 1)
uniform_tensor = torch.rand(2, 3)
print("\nTenseur aléatoire (distribution uniforme) :")
print(uniform_tensor)


Tenseur aléatoire (distribution uniforme) :
tensor([[0.9586, 0.1398, 0.4103],
        [0.2822, 0.3763, 0.2759]])


### 4.4 Créer des tenseurs semblables à un autre

Il est parfois utile de créer un tenseur ayant la même forme qu'un tenseur existant :


In [22]:
# Créer des tenseurs de même forme que x_tensor
zeros_like = torch.zeros_like(x_tensor)
ones_like = torch.ones_like(x_tensor)
rand_like = torch.randn_like(x_tensor.float())  # Remarque : randn requiert un type flottant

print("Forme du tenseur original :", x_tensor.shape)
print("Forme de zeros_like :", zeros_like.shape)
print("\nTenseur aléatoire de même forme :")
print(rand_like)

Forme du tenseur original : torch.Size([2, 3])
Forme de zeros_like : torch.Size([2, 3])

Tenseur aléatoire de même forme :
tensor([[-1.6212,  0.6933,  0.1268],
        [ 1.1194, -0.6022, -1.0711]])


In [23]:
zeros_like 

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [24]:
ones_like

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

## 5. Périphérique : CPU ou GPU

**Pourquoi les GPU sont importants :**
- Les GPU peuvent effectuer des milliers d'opérations en parallèle
- L'apprentissage profond implique des opérations matricielles massives → idéal pour les GPU
- L'entraînement peut être 10 à 100 fois plus rapide sur GPU que sur CPU

**Règle importante :** le modèle et les données doivent être sur le même périphérique !


In [25]:
# Vérifier le périphérique par défaut
x = torch.randn(2, 3)
print("Périphérique par défaut :", x.device)  # Généralement « cpu »

Périphérique par défaut : cpu


In [26]:
x.device

device(type='cpu')

In [27]:
# Vérifier si CUDA (GPU) est disponible et définir le périphérique
print("CUDA est-il disponible ?", torch.cuda.is_available())

CUDA est-il disponible ? False


In [30]:


# Utiliser le GPU si disponible, sinon le CPU
device = torch.device("mps" if torch.backends.mps.is_built() else "cpu")
print(f"Périphérique utilisé : {device}")



Périphérique utilisé : mps


In [31]:
# Déplacer le tenseur vers le périphérique
x = x.to(device)
print(f"Le tenseur est maintenant sur : {x.device}")

Le tenseur est maintenant sur : mps:0


**Conseil :** lorsque vous travaillez avec des modèles :
```python
model = MyModel().to(device)  # Move model to device
data = data.to(device)         # Move data to device
output = model(data)           # Now they can work together!
```


## 6. Vectorisation : écrire du code efficace

**Qu'est-ce que la vectorisation ?**

La vectorisation consiste à effectuer des opérations sur des tableaux entiers en une seule fois, plutôt que d'utiliser des boucles. Elle est :
- **Plus rapide** : elle exploite des implémentations bas niveau optimisées
- **Plus lisible** : moins de code, plus facile à lire
- **Plus Pythonique** : elle suit les bonnes pratiques

Voyons la différence :


In [32]:
import time

# Approche non vectorisée (LENTE)
x = torch.tensor([1, 2, 3, 4, 5])

start = time.time()
for i in range(len(x)):
    x[i] = x[i] + 5

time_loop = time.time() - start

print("Résultat non vectorisé :", x)

print(f"Temps : {time_loop:.6f} secondes")

Résultat non vectorisé : tensor([ 6,  7,  8,  9, 10])
Temps : 0.049324 secondes


In [33]:
# Approche vectorisée (RAPIDE)
x = torch.tensor([1, 2, 3, 4, 5])

start = time.time()

x = x + 5

time_vec = time.time() - start

print("Résultat vectorisé :", x)

print(f"Temps : {time_vec:.6f} secondes")

print(f"\nAccélération : {time_loop/time_vec:.1f}x plus rapide !")

Résultat vectorisé : tensor([ 6,  7,  8,  9, 10])
Temps : 0.000627 secondes

Accélération : 78.7x plus rapide !


### 6.1 Opérations vectorielles courantes

Implémentons des opérations fondamentales qui constituent les briques de base des réseaux de neurones.

#### Produit scalaire

Le produit scalaire de deux vecteurs $\mathbf{x}$ et $\mathbf{y}$ est :
$$\mathbf{x} \cdot \mathbf{y} = \sum_{i=1}^{n} x_i y_i = x_1y_1 + x_2y_2 + \cdots + x_ny_n$$

**Cas d'utilisation en apprentissage profond :**
- Calculer la similarité entre des vecteurs
- Multiplication matricielle (combinaison de produits scalaires)
- Mécanismes d'attention


In [34]:
def dot_product(x, y):
    """
    Calcule le produit scalaire de deux tenseurs 1D.

    Arguments :
        x: Tenseur 1D
        y: Tenseur 1D (même taille que x)

    Renvoie :
        Tenseur scalaire représentant le produit scalaire
    """
    return torch.dot(x, y)



In [35]:
# Exemple
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([4.0, 5.0, 6.0])
result = dot_product(x, y)
print(f"x · y = {result}")


x · y = 32.0


In [36]:
print(f"Calcul manuel : 1*4 + 2*5 + 3*6 = {1*4 + 2*5 + 3*6}")

Calcul manuel : 1*4 + 2*5 + 3*6 = 32


**📝 Exercice 1 : implémenter le produit scalaire**

Implémentez la fonction de produit scalaire à l'aide d'opérations PyTorch.


In [43]:
def PYTORCH_dot(x, y):
    """
    Produit scalaire de deux tenseurs.

    Paramètres :
        x (torch.Tensor): Tenseur 1D
        y (torch.Tensor): Tenseur 1D

    Renvoie :
        torch.Tenseur : Résultat scalaire du produit scalaire
    """
    # À FAIRE : implémenter avec torch.dot() ou un équivalent
    # Indice : vous pouvez utiliser torch.dot(x, y) ou (x * y).sum()
    return (x * y).sum()  # Remplacez cette ligne par votre implémentation

In [ ]:
# Testerer votre implémentation
np.random.seed(0)
X = np.random.randint(-1000, 1000, size=3000)
Y = np.random.randint(-1000, 1000, size=3000)
X = torch.tensor(X, dtype=torch.float32)
Y = torch.tensor(Y, dtype=torch.float32)

result = PYTORCH_dot(X, Y)
print(f"Résultat : {result}")
#print(f"Valeur attendue approximative : -222990528.0")

Résultat : 7082792.0
Valeur attendue approximative : -222990528.0


#### Produit extérieur

Le produit extérieur des vecteurs $\mathbf{x}$ (taille $m$) et $\mathbf{y}$ (taille $n$) produit une matrice :
$$\mathbf{x} \otimes \mathbf{y} = \mathbf{x}\mathbf{y}^T = \begin{bmatrix} x_1y_1 & x_1y_2 & \cdots \\ x_2y_1 & x_2y_2 & \cdots \\ \vdots & \vdots & \ddots \end{bmatrix}$$

**Utilisation en apprentissage profond :** calcul des poids d'attention, couches bilinéaires


In [42]:
def PYTORCH_outer(x, y):
    """
    Calcule le produit extérieur de deux vecteurs.

    Paramètres :
        x (torch.Tensor): Tenseur 1D of shape (m,)
        y (torch.Tensor): Tenseur 1D of shape (n,)

    Renvoie :
        torch.Tenseur : Tenseur 2D de forme (m, n)
    """
    # À FAIRE : implémenter avec torch.outer() ou un remodelage suivi d’une multiplication
    # Indice : torch.outer(x, y) ou x.unsqueeze(1) * y.unsqueeze(0)
    return torch.outer(x, y)  # Remplacez cette ligne par votre implémentation

In [45]:
PYTORCH_outer(X, Y)

tensor([[  59092., -144096.,  136512.,  ...,  -53088.,  -86268.,   53404.],
        [  82467., -201096.,  190512.,  ...,  -74088., -120393.,   74529.],
        [-122111.,  297768., -282096.,  ...,  109704.,  178269., -110357.],
        ...,
        [-144551.,  352488., -333936.,  ...,  129864.,  211029., -130637.],
        [-179707.,  438216., -415152.,  ...,  161448.,  262353., -162409.],
        [  88825., -216600.,  205200.,  ...,  -79800., -129675.,   80275.]])

#### Produit élément par élément (Hadamard)

Multiplication élément par élément : $\mathbf{z} = \mathbf{x} \odot \mathbf{y}$ où $z_i = x_i \times y_i$

**Utilisation en apprentissage profond :** mécanismes de porte (LSTM, GRU), masquage d'attention


In [47]:
def PYTORCH_multiply(x, y):
    """
    Multiplie les arguments élément par élément.

    Paramètres :
        x (torch.Tensor): Tenseur d’entrée
        y (torch.Tensor): Tenseur d’entrée (same shape as x)

    Renvoie :
        torch.Tenseur : Produit élément par élément
    """
    # À FAIRE : implémenter avec l’opérateur * ou torch.mul()
    return torch.mul(x,y)

#### Fonction d'activation ReLU

ReLU (unité linéaire rectifiée) est l'une des fonctions d'activation les plus populaires :
$$\text{ReLU}(x) = \max(0, x) = \begin{cases} x & \text{si } x > 0 \\ 0 & \text{si } x \leq 0 \end{cases}$$

**Pourquoi ReLU ?**
- Aide à résoudre le problème de disparition du gradient
- Efficace en calcul
- Introduit de la non-linéarité

**Illustration :**
- Entrée : `[-2, -1, 0, 1, 2]`
- Sortie : `[0, 0, 0, 1, 2]`


In [49]:
def PYTORCH_ReLU(x):
    """
    Applique la fonction unité linéaire rectifiée élément par élément.

    Paramètres :
        x (torch.Tensor): Tenseur d’entrée

    Renvoie :
        torch.Tenseur : ReLU appliquée élément par élément
    """
    # À FAIRE : implémenter avec torch.relu() ou torch.maximum()
    # Indice : torch.relu(x) ou torch.maximum(x, torch.tensor(0.0))
    return torch.maximum(x, torch.tensor(0.0))

In [50]:
# Exemple de ReLU
x = torch.tensor([-2.0, -1.0, 0.0, 1.0, 2.0])
output = torch.relu(x)
print(f"Entrée :  {x}")
print(f"Sortie : {output}")

Entrée :  tensor([-2., -1.,  0.,  1.,  2.])
Sortie : tensor([0., 0., 0., 1., 2.])


## 7. Manipulation des tenseurs

La manipulation des formes des tenseurs est essentielle en apprentissage profond. Vous devrez souvent remodeler les données pour répondre aux exigences du modèle.

### 7.1 Reshape et View

**reshape ou view :**
- `view()` : renvoie une vue des mêmes données (nécessite une mémoire contiguë)
- `reshape()` : plus flexible, peut copier les données si nécessaire


In [51]:
# Exemple : remodelage d’un tenseur
x = torch.randn(4, 6)  # 4x6 = 24 elements
print("Forme originale :", x.shape)



Forme originale : torch.Size([4, 6])


In [54]:
4*6

24

In [52]:
x

tensor([[ 1.4166,  1.0418,  0.4042, -1.2784,  1.7079, -0.0993],
        [-0.3287, -0.7630, -0.7673, -0.0067,  1.3072,  1.2333],
        [ 0.5613, -0.5062,  0.2980, -1.5015, -0.4808, -2.4454],
        [ 1.6845, -0.4127, -0.4373,  0.8974, -0.6323,  0.5648]])

In [55]:
# Remodeler avec d’autres dimensions (en conservant le même nombre d’éléments)
y = x.view(2, 12)     # 2x12 = 24 elements


In [57]:
y.shape

torch.Size([2, 12])

In [64]:
z = x.reshape(8, 3)   # 8x3 = 24 elements

In [59]:
z

tensor([[ 1.4166,  1.0418,  0.4042],
        [-1.2784,  1.7079, -0.0993],
        [-0.3287, -0.7630, -0.7673],
        [-0.0067,  1.3072,  1.2333],
        [ 0.5613, -0.5062,  0.2980],
        [-1.5015, -0.4808, -2.4454],
        [ 1.6845, -0.4127, -0.4373],
        [ 0.8974, -0.6323,  0.5648]])

In [67]:

w = x.view(-1)        # -1 déduit la dimension: 24



In [62]:
w.shape

torch.Size([24])

In [66]:
print("Remodelé en (2, 12):", y.shape)
print("Remodelé en (8, 3):", z.shape)
print("Aplati en 1D :", w.shape)

Remodelé en (2, 12): torch.Size([2, 12])
Remodelé en (8, 3): torch.Size([8, 3])
Aplati en 1D : torch.Size([24])


**⚠️ Important :** le nombre total d'éléments doit rester identique !
- Valide : `(4, 6)` → `(2, 12)` ✓
- Non valide : `(4, 6)` → `(5, 5)` ✗ (24 ≠ 25)


### 7.2 Squeeze et Unsqueeze

**squeeze()** : supprime les dimensions de taille 1
**unsqueeze()** : ajoute une dimension de taille 1

Ces opérations sont utiles pour faire correspondre les dimensions lors des calculs.


In [68]:
# Unsqueeze : ajouter une dimension
x = torch.tensor([1, 2, 3, 4])  # Forme : (4,)
print("Original :", x.shape)



Original : torch.Size([4])


In [69]:
x_unsqueezed = x.unsqueeze(0)   # Ajouter une dimension à la position 0
print("Après unsqueeze (dim=0):", x_unsqueezed.shape)  # (1, 4)

Après unsqueeze (dim=0): torch.Size([1, 4])


In [70]:


x_unsqueezed = x.unsqueeze(1)   # Ajouter une dimension à la position 1
print("Après unsqueeze (dim=1):", x_unsqueezed.shape)  # (4, 1)

Après unsqueeze (dim=1): torch.Size([4, 1])


In [71]:
# Squeeze : supprimer une dimension de taille 1
x = torch.randn(1, 3, 1, 4)
print("Original :", x.shape)

Original : torch.Size([1, 3, 1, 4])


In [74]:
x

tensor([[[[ 0.3195,  0.5704, -0.8463,  1.3101]],

         [[-1.3175, -0.6041, -0.1942,  0.4169]],

         [[ 0.8553, -1.2245,  0.1508, -0.7575]]]])

In [75]:
x_squeezed = x.squeeze()  # Supprimer toutes les dimensions de taille 1
print("Après tous les squeeze :", x_squeezed.shape)  # (3, 4)

Après tous les squeeze : torch.Size([3, 4])


In [76]:




x_squeezed = x.squeeze(0)  # Supprimer une dimension spécifique
print("Dimension après squeeze 0:", x_squeezed.shape)  # (3, 1, 4)

Dimension après squeeze 0: torch.Size([3, 1, 4])


### 7.3 Transpose et Permute

**transpose()** : échange deux dimensions
**permute()** : réorganise toutes les dimensions

Utilisation courante : conversion entre différents formats de données (p. ex. canaux en dernier ↔ canaux en premier)


In [77]:
# Transpose : échanger deux dimensions spécifiques
x = torch.randn(2, 3, 4)  # (batch, height, width)
print("Original :", x.shape)

x_t = x.transpose(0, 1)  # Échanger les dimensions 0 et 1
print("Après transposition (0,1):", x_t.shape)  # (3, 2, 4)

Original : torch.Size([2, 3, 4])
Après transposition (0,1): torch.Size([3, 2, 4])


In [78]:
# Permute : réorganiser toutes les dimensions
x = torch.randn(2, 3, 4, 5)  # (batch, channels, height, width)
print("Original (B,C,H,W):", x.shape)

# Réorganiser en (batch, height, width, channels)
x_p = x.permute(0, 2, 3, 1)
print("Après permutation (B,H,W,C):", x_p.shape)  # (2, 4, 5, 3)

Original (B,C,H,W): torch.Size([2, 3, 4, 5])
Après permutation (B,H,W,C): torch.Size([2, 4, 5, 3])


### 7.4 Concaténer et empiler

**cat()** : concatène des tenseurs le long d'une dimension existante
**stack()** : empile des tenseurs le long d'une nouvelle dimension


In [79]:
# Concaténer le long d’une dimension existante
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

# Concaténer le long des lignes (dim=0)
cat_0 = torch.cat([x, y], dim=0)
print("Concaténé (dim=0):")
print(cat_0)
print("Forme :", cat_0.shape)  # (4, 2)

# Concaténer le long des colonnes (dim=1)
cat_1 = torch.cat([x, y], dim=1)
print("\nConcaténé (dim=1):")
print(cat_1)
print("Forme :", cat_1.shape)  # (2, 4)

Concaténé (dim=0):
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
Forme : torch.Size([4, 2])

Concaténé (dim=1):
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
Forme : torch.Size([2, 4])


In [80]:
# Stack : créer une nouvelle dimension
stacked = torch.stack([x, y], dim=0)
print("Empilé (dim=0):")
print(stacked)
print("Forme :", stacked.shape)  # (2, 2, 2)

stacked_1 = torch.stack([x, y], dim=1)
print("\nEmpilé (dim=1) shape:", stacked_1.shape)  # (2, 2, 2)

Empilé (dim=0):
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Forme : torch.Size([2, 2, 2])

Empilé (dim=1) shape: torch.Size([2, 2, 2])


## 8. Différentiation automatique (Autograd)

**Pourquoi Autograd est essentiel :**

L'entraînement des réseaux de neurones exige le calcul de gradients (dérivées) pour la rétropropagation. Le système autograd de PyTorch s'en charge automatiquement !

**Concepts clés :**
- `requires_grad=True` : indique à PyTorch de suivre les opérations
- `.backward()` : calcule automatiquement les gradients
- `.grad` : stocke le gradient calculé

### 8.1 Exemple simple

Calculons $\frac{dy}{dx}$ où $y = x^2$


In [82]:
# Calcul simple de gradient
x = torch.tensor(2.0, requires_grad=True)  # Suivre ce tenseur
y = x**2  # y = 4.0

In [83]:
print(f"y = {y}")
print(f"dy/dx analytiquement = 2x = {2 * 2}")

y = 4.0
dy/dx analytiquement = 2x = 4


In [84]:




# Calculer le gradient
y.backward()  # Compute dy/dx
print(f"dy/dx (calculé) = {x.grad}")

dy/dx (calculé) = 4.0


**Que s'est-il passé ?**
1. Nous avons créé `x` avec `requires_grad=True`
2. PyTorch a suivi toutes les opérations sur `x` (sa mise au carré)
3. `.backward()` a calculé automatiquement le gradient
4. Le résultat est stocké dans `x.grad`


### 8.2 Exemple plus complexe

Calculons les gradients de : $y = a^2 + c \cdot b$

Alors :
- $\frac{\partial y}{\partial a} = 2a$
- $\frac{\partial y}{\partial b} = c$
- $\frac{\partial y}{\partial c} = b$


In [ ]:
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(4.0, requires_grad=True)
c = torch.tensor(3.0, requires_grad=True)

y = a**2 + c * b
print(f"y = {y}")

y.backward()

print(f"\nGradients :")
print(f"∂y/∂a = {a.grad} (attendu : 2*2 = 4)")
print(f"∂y/∂b = {b.grad} (attendu : c = 3)")
print(f"∂y/∂c = {c.grad} (attendu : b = 4)")

### 8.3 Graphe de calcul

PyTorch construit un **graphe de calcul** qui suit toutes les opérations :

```
     a           b        c
     |           |        |
   square       mul ------+
     |           |
     +----add----+
          |
          y
```

Pendant `.backward()`, PyTorch parcourt ce graphe en sens inverse pour calculer les gradients.


In [ ]:
# Inspecter le graphe de calcul
x = torch.tensor(2.0, requires_grad=True)
y = x**2 + 3*x + 1

print("y.grad_fn:", y.grad_fn)  # Affiche la dernière opération
print("\nStructure du graphe de calcul :")
print("y.grad_fn.next_functions:", y.grad_fn.next_functions)

### 8.4 ⚠️ Important : les gradients s'accumulent !

Par défaut, appeler `.backward()` plusieurs fois **additionne** les gradients au lieu de les remplacer.


In [85]:
# Accumulation de gradients (généralement indésirable !)
x = torch.tensor(2.0, requires_grad=True)

for step in range(3):
    y = x**2
    y.backward()  # Les gradients s’accumulent !
    print(f"Étape {step+1}: x.grad = {x.grad}")

Étape 1: x.grad = 4.0
Étape 2: x.grad = 8.0
Étape 3: x.grad = 12.0


**Solution :** effacez les gradients avant chaque passe arrière :


In [86]:
# Gestion correcte des gradients
x = torch.tensor(2.0, requires_grad=True)

for step in range(3):
    if x.grad is not None:
        x.grad.zero_()  # Effacer les gradients précédents

    y = x**2
    y.backward()
    print(f"Étape {step+1}: x.grad = {x.grad}")

Étape 1: x.grad = 4.0
Étape 2: x.grad = 4.0
Étape 3: x.grad = 4.0


**En pratique :**
```python
# Training loop pattern
optimizer.zero_grad()  # Clear gradients
output = model(input)  # Forward pass
loss = criterion(output, target)
loss.backward()        # Compute gradients
optimizer.step()       # Update weights
```


## 9. Construire un réseau de neurones

Rassemblons maintenant tous les éléments et construisons un réseau de neurones complet pour classifier des chiffres manuscrits !

**Jeu de données :** MNIST (images en niveaux de gris 28×28 des chiffres de 0 à 9)

**Architecture :**
```
Entrée (784) → Cachée (128) → Sortie (10)
    ↓            ↓              ↓
 Aplatissement   ReLU         Softmax
```


### 9.1 Importer les bibliothèques requises


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

### 9.2 Préparer le jeu de données

Nous allons :
1. Télécharger le jeu de données MNIST
2. Normaliser les images dans l'intervalle [-1, 1]
3. Créer des chargeurs de données pour les lots


In [ ]:
# Transformation : convertir les images en tenseurs et normaliser
transform = transforms.Compose([
    transforms.ToTensor(),                    # Convertir en tenseur
    transforms.Normalize((0.5,), (0.5,))     # Normaliser dans [-1, 1]
])

# Télécharger et charger les données d’entraînement
train_dataset = datasets.MNIST(
    root='./data',
    train=True,
    download=True,
    transform=transform
)

# Télécharger et charger les données de test
test_dataset = datasets.MNIST(
    root='./data',
    train=False,
    download=True,
    transform=transform
)

# Créer les chargeurs de données
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

print(f"Exemples d’entraînement : {len(train_dataset)}")
print(f"Exemples de test : {len(test_dataset)}")

### 9.3 Définir le réseau de neurones

Nous allons créer un réseau de neurones simple à propagation avant avec :
- Couche d'entrée : 784 neurones (pixels 28×28 aplatis)
- Couche cachée : 128 neurones avec activation ReLU
- Couche de sortie : 10 neurones (un par classe de chiffre)


In [ ]:
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()

        # Définir les couches
        self.flatten = nn.Flatten()           # Aplatir 28x28 en 784
        self.fc1 = nn.Linear(784, 128)        # Première couche entièrement connectée
        self.fc2 = nn.Linear(128, 10)         # Couche de sortie

    def forward(self, x):
        """Passe avant à travers le réseau"""
        x = self.flatten(x)          # Aplatir : (batch, 1, 28, 28) → (batch, 784)
        x = self.fc1(x)              # Première couche
        x = F.relu(x)                # Activation ReLU
        x = self.fc2(x)              # Couche de sortie
        return x                     # Logits bruts (softmax appliqué dans la perte)

# Créer le modèle et le déplacer vers le périphérique
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = SimpleNN().to(device)
print(model)
print(f"\nLe modèle est sur : {next(model.parameters()).device}")

**Comprendre l'architecture :**

1. **Flatten** : convertit une image 2D en vecteur 1D
2. **fc1** : apprend 128 caractéristiques à partir de l'entrée
3. **ReLU** : ajoute de la non-linéarité
4. **fc2** : associe les caractéristiques à 10 scores de classe


### 9.4 Définir la fonction de perte et l'optimiseur

**Fonction de perte :** CrossEntropyLoss (combine softmax et log-vraisemblance négative)
**Optimiseur :** SGD (descente de gradient stochastique)


In [ ]:
# Fonction de perte
criterion = nn.CrossEntropyLoss()

# Optimiseur : met à jour les poids du modèle selon les gradients
optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.9)

print("Fonction de perte:", criterion)
print("Optimiseur :", optimizer)

### 9.5 Boucle d'entraînement

Le processus d'entraînement :
1. **Passe avant** : calculer les prédictions
2. **Calculer la perte** : dans quelle mesure le modèle se trompe-t-il ?
3. **Passe arrière** : calculer les gradients
4. **Mettre à jour les poids** : améliorer le modèle


In [ ]:
# Boucle d’entraînement
num_epochs = 3
print('Début de l’entraînement\n')

for epoch in range(num_epochs):
    model.train()  # Mettre le modèle en mode entraînement
    running_loss = 0.0

    for batch_idx, (images, labels) in enumerate(train_loader):
        # Déplacer les données vers le périphérique
        images, labels = images.to(device), labels.to(device)

        # Réinitialiser les gradients
        optimizer.zero_grad()

        # Passe avant
        outputs = model(images)
        loss = criterion(outputs, labels)

        # Passe arrière et optimisation
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        # Afficher la progression
        if batch_idx % 200 == 0:
            print(f'Époque [{epoch+1}/{num_epochs}], '
                  f'Étape [{batch_idx}/{len(train_loader)}], '
                  f'Perte : {loss.item():.4f}')

    # Afficher les statistiques de l’époque
    avg_loss = running_loss / len(train_loader)
    print(f'Époque [{epoch+1}/{num_epochs}] Perte moyenne : {avg_loss:.4f}\n')

print('Finished Training!')

### 9.6 Évaluer le modèle

Testons notre modèle entraîné sur l'ensemble de test !


In [ ]:
# Évaluation
model.eval()  # Mettre le modèle en mode évaluation
correct = 0
total = 0

with torch.no_grad():  # Désactiver le calcul des gradients
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)  # Obtenir la classe au score le plus élevé

        total += labels.size(0)
        correct += (predicted == labels).sum().item()

accuracy = 100 * correct / total
print(f'Précision sur 10 000 images de test : {accuracy:.2f}%')
print(f'Prédictions correctes : {correct}/{total}')

### 9.7 Visualiser les prédictions

Observons quelques prédictions réelles :


In [ ]:
import matplotlib.pyplot as plt

# Obtenir un lot d’images de test
dataiter = iter(test_loader)
images, labels = next(dataiter)
images, labels = images.to(device), labels.to(device)

# Faire des prédictions
model.eval()
with torch.no_grad():
    outputs = model(images)
    _, predictions = torch.max(outputs, 1)

# Déplacer vers le CPU pour le tracé
images = images.cpu()
predictions = predictions.cpu()
labels = labels.cpu()

# Tracer les 10 premières images
fig, axes = plt.subplots(2, 5, figsize=(12, 5))
for i, ax in enumerate(axes.flat):
    ax.imshow(images[i].squeeze(), cmap='gray')
    ax.set_title(f'Préd. : {predictions[i]}, Vrai : {labels[i]}')
    ax.axis('off')
plt.tight_layout()
plt.show()

## 10. Résumé et bonnes pratiques

### Points essentiels

1. Les **tenseurs** sont la structure de données fondamentale de PyTorch
   - Similaires aux tableaux NumPy, mais compatibles GPU
   - Prennent en charge la différentiation automatique

2. **Autograd** calcule automatiquement les gradients
   - Utilisez `requires_grad=True` pour suivre les opérations
   - Appelez `.backward()` pour calculer les gradients
   - N'oubliez pas de réinitialiser les gradients !

3. Les **réseaux de neurones** sont construits avec `nn.Module`
   - Définissez les couches dans `__init__`
   - Implémentez la passe avant dans `forward()`
   - Utilisez les fonctions de perte et les optimiseurs intégrés

### Bonnes pratiques

#### 1. Gestion des périphériques
```python
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = model.to(device)
data = data.to(device)
```

#### 2. Structure de la boucle d'entraînement
```python
model.train()  # Training mode
for images, labels in train_loader:
    optimizer.zero_grad()      # Clear gradients
    outputs = model(images)    # Forward pass
    loss = criterion(outputs, labels)
    loss.backward()            # Backward pass
    optimizer.step()           # Update weights
```

#### 3. Mode évaluation
```python
model.eval()  # Evaluation mode
with torch.no_grad():  # Disable gradient computation
    outputs = model(test_data)
```

#### 4. Sauvegarder et charger des modèles
```python
# Save
torch.save(model.state_dict(), 'model.pth')

# Load
model.load_state_dict(torch.load('model.pth'))
```

### Erreurs courantes à éviter

❌ **Oublier de réinitialiser les gradients**
```python
# Wrong - gradients accumulate!
loss.backward()
optimizer.step()
```
✅ **Correct**
```python
optimizer.zero_grad()
loss.backward()
optimizer.step()
```

❌ **Modèle et données sur des périphériques différents**
```python
model = model.to('cuda')
output = model(data)  # data still on CPU - Error!
```
✅ **Correct**
```python
model = model.to(device)
data = data.to(device)
output = model(data)
```

❌ **Oublier d'appeler `.eval()` pendant les tests**
```python
# Wrong - dropout/batchnorm still active
with torch.no_grad():
    output = model(test_data)
```
✅ **Correct**
```python
model.eval()
with torch.no_grad():
    output = model(test_data)
```


## 11. Exercices pratiques

### Exercice 1 : implémenter des opérations vectorielles supplémentaires

Implémentez ces fonctions avec PyTorch :
1. **Somme-produit** : somme de tous les éléments du produit extérieur
2. **Dérivée de ReLU** : dérivée de ReLU (1 si x > 0, sinon 0)
3. **Sigmoïde** : $\sigma(x) = \frac{1}{1 + e^{-x}}$


In [ ]:
# Exercice 1.1 : somme-produit
def sum_product(x, y):
    """
    Somme de tous les éléments du produit extérieur.
    Indice : combiner le produit extérieur avec .sum()
    """
    # VOTRE CODE ICI
    pass

# Tester
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([4.0, 5.0])
# Attendu : (1+2+3) * (4+5) = 6 * 9 = 54
# print(f"Résultat : {sum_product(x, y)}")

In [ ]:
# Exercice 1.2 : dérivée de ReLU
def relu_derivative(x):
    """
    Dérivée de ReLU : 1 si x > 0, sinon 0
    Indice : utiliser les opérateurs de comparaison et .float()
    """
    # VOTRE CODE ICI
    pass

# Tester
x = torch.tensor([-2.0, -1.0, 0.0, 1.0, 2.0])
# Attendu : [0, 0, 0, 1, 1]
# print(f"Résultat : {relu_derivative(x)}")

In [ ]:
# Exercice 1.3 : sigmoïde
def sigmoid(x):
    """
    Activation sigmoïde : 1 / (1 + exp(-x))
    Indice : utiliser torch.exp()
    """
    # VOTRE CODE ICI
    pass

# Tester
x = torch.tensor([0.0, 1.0, -1.0])
# Attendu : [0.5, 0.731, 0.269] (environ)
# print(f"Résultat : {sigmoid(x)}")

### Exercice 2 : construire un réseau plus profond

Modifiez SimpleNN pour ajouter :
1. Une autre couche cachée (128 → 64 neurones)
2. Du dropout pour la régularisation
3. Une normalisation par lot


In [ ]:
class ImprovedNN(nn.Module):
    def __init__(self):
        super(ImprovedNN, self).__init__()

        # À FAIRE : définir vos couches
        # Indice : utiliser nn.Linear, nn.Dropout, nn.BatchNorm1d
        pass

    def forward(self, x):
        # À FAIRE : implémenter la passe avant
        pass

# Testerer votre modèle
# model = ImprovedNN()
# print(model)

### Exercice 3 : expérimenter avec les hyperparamètres

Essayez de modifier :
- Le taux d'apprentissage (0.001, 0.01, 0.1)
- La taille des lots (32, 64, 128)
- Le nombre d'époques (1, 3, 5)
- L'optimiseur (SGD, Adam, RMSprop)

Observez comment ils influencent la vitesse d'entraînement et la précision finale !


## 12. Ressources supplémentaires

### Documentation officielle
- [Documentation PyTorch](https://pytorch.org/docs/stable/index.html) - Référence complète de l'API
- [Tutoriels PyTorch](https://pytorch.org/tutorials/) - Tutoriels officiels
- [Exemples PyTorch](https://github.com/pytorch/examples) - Implémentations d'exemple

### Ressources d'apprentissage
- [Deep Learning with PyTorch](https://pytorch.org/assets/deep-learning/Deep-Learning-with-PyTorch.pdf) - Livre gratuit
- [PyTorch Lightning](https://www.pytorchlightning.ai/) - Framework de haut niveau
- [Papers with Code](https://paperswithcode.com/) - Dernières implémentations de recherche

### Outils et bibliothèques
- **torchvision** : jeux de données et modèles de vision par ordinateur
- **torchaudio** : traitement audio
- **torchtext** : traitement automatique du langage naturel
- **TensorBoard** : outil de visualisation

### Concepts importants à étudier ensuite
1. **Réseaux de neurones convolutionnels (CNN)** pour le traitement d'images
2. **Réseaux de neurones récurrents (RNN/LSTM)** pour les séquences
3. **Transformers** pour le NLP moderne
4. **Apprentissage par transfert** avec des modèles préentraînés
5. **Augmentation des données** pour une meilleure généralisation

### Conseils utiles
- Vérifiez toujours les formes des tenseurs lors du débogage
- Utilisez `print(model)` pour vérifier l'architecture
- Surveillez l'entraînement avec des outils de visualisation
- Commencez simplement, puis ajoutez de la complexité
- Lisez attentivement les messages d'erreur : ils sont généralement utiles !

---

## Bon courage dans votre parcours d'apprentissage profond ! 🚀

*N'oubliez pas : la pratique est essentielle. Essayez de construire différents modèles et d'expérimenter avec divers jeux de données !*


## Aide-mémoire de référence rapide

### Création de tenseurs
```python
torch.tensor([1, 2, 3])          # From list
torch.zeros(2, 3)                # Zeros
torch.ones(2, 3)                 # Ones
torch.randn(2, 3)                # Random normal
torch.rand(2, 3)                 # Random uniform
```

### Opérations sur les tenseurs
```python
x + y, x - y, x * y, x / y      # Element-wise ops
x @ y, torch.mm(x, y)           # Matrix multiplication
x.dot(y)                         # Dot product
x.reshape(2, 3)                  # Reshape
x.view(-1)                       # Flatten
```

### Autograd
```python
x = torch.tensor(2.0, requires_grad=True)
y = x**2
y.backward()       # Compute gradients
print(x.grad)      # Access gradient
x.grad.zero_()     # Clear gradient
```

### Bases des réseaux de neurones
```python
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer = nn.Linear(10, 5)
    
    def forward(self, x):
        return self.layer(x)
```

### Couches courantes
```python
nn.Linear(in_features, out_features)  # Fully connected
nn.Conv2d(in_ch, out_ch, kernel_size) # 2D convolution
nn.MaxPool2d(kernel_size)             # Max pooling
nn.Dropout(p=0.5)                     # Dropout
nn.BatchNorm1d(num_features)          # Batch norm
```

### Fonctions d'activation
```python
F.relu(x)
F.sigmoid(x)
F.tanh(x)
F.softmax(x, dim=1)
```
