In [4]:
import torch.nn as nn # import neural network module from pytorch
import torch


In [3]:
# créons un tensor composé de 3 éléments 

input_tensor = torch.tensor([0.34, 0.302, -1.404], dtype=torch.float32)

In [ ]:
# taille
28*28 = 
224*224 = 

In [9]:
# definir le layer

layer = nn.Linear(
    in_features=3,  # nombre d'éléments dans le tensor d'entrée
    out_features=2,  # nombre d'éléments dans le tensor de sortie
)

In [7]:
output_tensor = layer(input_tensor)
output_tensor

tensor([-0.0967, -0.0003], grad_fn=<ViewBackward0>)

In [11]:
print("weight", layer.weight)

weight Parameter containing:
tensor([[-0.5766, -0.1912, -0.4012],
        [-0.0523, -0.4127,  0.3784]], requires_grad=True)


In [12]:
print("biais" ,layer.bias)

biais Parameter containing:
tensor([ 0.2363, -0.5517], requires_grad=True)


In [16]:
n_classes = 2
n_features = 3

In [15]:
# MLP
model = nn.Sequential(
    nn.Linear(n_features, 8),
    nn.Linear(8, 4),
    nn.Linear(4, n_classes)
)

In [17]:
model = nn.Sequential(
    nn.Linear(8,4),
    nn.Linear(4,2))

In [20]:
#calculons le nombre de paramètres du modèle
total = 0

for params in model.parameters():
    total += params.numel()
    #print(params.numel())

total

46